### ISSUE TITLE
Running NEB with mofilesdir through Knarr interface

### ISSUE THREAD

**Issue by Lisa-Phan** [RagnarB83/ash#419]
Hello, 

Firstly, I just want to say thank you for creating and maintaining this project. I'm trying to use the ASH interface with Knarr to run a transition state search. I had tested an NEB job that takes in a starting and ending structure, which runs ok in parallel. However, when I tried the option of reading in images with guess, there is an error. The job would finish doing calculation for the reactant and product image, and exit after attempting to read in the intermediate images:
"""
 ------------ENDING ORCA-INTERFACE------------- 

----------------------------------------------------------------
Time to calculate step (ORCA run): 164.601 seconds, 2.7 minutes.
----------------------------------------------------------------
 ASH exiting with code: 1 
Found possible error messages in ORCA outputfile:
[v320-013:687402] *** An error occurred in MPI_Init
 [v320-013:687402] *** Unknown error
 ORCA finished by error termination in GTOInt
 [v320-013.ls6.tacc.utexas.edu:687410] ../../../../../ompi/mca/pml/ucx/pml_ucx.c:309  Error: Failed to create UCP worker
 [v320-013.ls6.tacc.utexas.edu:687412] ../../../../../ompi/mca/pml/ucx/pml_ucx.c:309  Error: Failed to create UCP worker
 [v320-013.ls6.tacc.utexas.edu:687407] ../../../../../ompi/mca/pml/ucx/pml_ucx.c:309  Error: Failed to create UCP worker
 [v320-013.ls6.tacc.utexas.edu:687408] ../../../../../ompi/mca/pml/ucx/pml_ucx.c:309  Error: Failed to create UCP worker
 [v320-013.ls6.tacc.utexas.edu:687404] ../../../../../ompi/mca/pml/ucx/pml_ucx.c:309  Error: Failed to create UCP worker
 [v320-013.ls6.tacc.utexas.edu:687405] ../../../../../ompi/mca/pml/ucx/pml_ucx.c:309  Error: Failed to create UCP worker
 [v320-013.ls6.tacc.utexas.edu:687409] ../../../../../ompi/mca/pml/ucx/pml_ucx.c:309  Error: Failed to create UCP worker
 [v320-013.ls6.tacc.utexas.edu:687402] ../../../../../ompi/mca/pml/ucx/pml_ucx.c:309  Error: Failed to create UCP worker
 [v320-013.ls6.tacc.utexas.edu:687406] ../../../../../ompi/mca/pml/ucx/pml_ucx.c:309  Error: Failed to create UCP worker
 [1716945702.895224] [v320-013:687410:0]         ib_mlx5.c:128  UCX  ERROR mlx5_0: mlx5dv_create_cq(cqe=4096) failed: Invalid argument
 [1716945754.666395] [v320-013:687412:0]         ib_mlx5.c:128  UCX  ERROR mlx5_0: mlx5dv_create_cq(cqe=4096) failed: Invalid argument
 [1716945765.145008] [v320-013:687407:0]         ib_mlx5.c:128  UCX  ERROR mlx5_0: mlx5dv_create_cq(cqe=4096) failed: Invalid argument
 [1716945765.240198] [v320-013:687408:0]         ib_mlx5.c:128  UCX  ERROR mlx5_0: mlx5dv_create_cq(cqe=4096) failed: Invalid argument
 [1716945765.329063] [v320-013:687404:0]         ib_mlx5.c:128  UCX  ERROR mlx5_0: mlx5dv_create_cq(cqe=4096) failed: Invalid argument
 [1716945771.341025] [v320-013:687405:0]         ib_mlx5.c:128  UCX  ERROR mlx5_0: mlx5dv_create_cq(cqe=4096) failed: Invalid argument
 [1716945771.759827] [v320-013:687409:0]         ib_mlx5.c:128  UCX  ERROR mlx5_0: mlx5dv_create_cq(cqe=4096) failed: Invalid argument
 [1716945775.732980] [v320-013:687402:0]         ib_mlx5.c:128  UCX  ERROR mlx5_0: mlx5dv_create_cq(cqe=4096) failed: Invalid argument
 [1716945779.957300] [v320-013:687406:0]         ib_mlx5.c:128  UCX  ERROR mlx5_0: mlx5dv_create_cq(cqe=4096) failed: Invalid argument
 [v320-013:687402] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort
"""
 

Beneath is the environment setup that I'm using. These are ran on TACC HPC Cluster. 

"""
#environment configuration
#orca 4.1.1
export ORCA=/work/09069/dhp563/ls6/orcaa/all_three/orca

module use /scratch/projects/compilers/nvhpc_23.7/Linux_x86_64/23.7/comm_libs/12.2/hpcx/hpcx-2.15/modulefiles/
module use /scratch/projects/compilers/nvhpc_23.7/modulefiles/
module load nvhpc-hpcx-cuda12
module load hpcx
module unload intel impi

conda activate ash
"""

 This was the python code used 
 """
REACTANT = r"/scratch/09069/dhp563/ash/test/amber/coords/reactant.xyz"
PRODUCT = r"/scratch/09069/dhp563/ash/test/amber/coords/product.xyz"

import textwrap 
import os
from ash import *

#configure orca related environment variables
os.system("source $HOME/orca_env_config.sh")

reactant = Fragment(xyzfile=REACTANT, conncalc=False, charge = 0, mult = 11)
product = Fragment(xyzfile=PRODUCT, conncalc=False, charge = 0, mult = 11)
#NEB-CI job. Final saddlepoint structure stored in new object "Saddlepoint"

#create Orca theory from simple input and blocks
input = "!BP86 def2-SVP TightSCF"
block = textwrap.dedent("""
    %basis
    newgto Fe "def2-TZVP" end
    newgto O "def2-TZVP" end
    newgto N "def2-TZVP" end
    end
                        
    %scf
    CNVZerner True
    end
                                            
    """)

theory_obj = ORCATheory(orcasimpleinput = input, 
                        orcablocks = block, 
                        numcores = 10, 
                        orcadir = r"/work/09069/dhp563/ls6/orcaa/all_three")

Saddlepoint = interfaces.interface_knarr.NEB(reactant = reactant, 
                                             product = product, 
                                             theory = theory_obj, 
                                             images=8, 
                                             CI=True,  
                                             runmode = 'parallel', 
                                             numcores = 10, 
                                             mofilesdir = r"/scratch/09069/dhp563/ash/test/orca_neb/pmul_neb/pmul_file_collection_troubleshoot/renamed_gbw_file")

Saddlepoint.print_system(filename='saddlepoint_PQ.ygg')
"""
 The files used for the images are the .gbw generated previously by Orca, and can be found here
 https://zenodo.org/records/11188664?token=eyJhbGciOiJIUzUxMiJ9.eyJpZCI6IjM1NWE2MjliLWNiNGItNDJmYy1hMzk0LWNhZjlmYWQ1Yzk1ZSIsImRhdGEiOnt9LCJyYW5kb20iOiJiMjZhMGU3NjY5OTFkOGFmYThhNzk5NWVmMGEyOTA2NiJ9.sEvnvcY-ZENkxxaYPV5uJJU4EDvCffsXipL7h5yNv86lnmqJqz7yvLMUhOB11Syv4sSKA_BHt9dhQvzj-iEK9A
 
Please let me know if there is other information I should include. 

Thank you very much, 
Lisa Phan

**Comment by RagnarB83** [comment]
Sorry for the late reply.
It's a little tricky to understand why it worked fine but not with the mofilesdir option. But it has to do with the parallelization of ORCA (since we have an OpenMPI error). 
Actually, if you are running NEB in parallel (i.e. runmode='parallel' option), specifying 8 images then ASH will parallelize over the images (running 8 images at the same time on 8 cores) but you should then turn the ORCA-parallelization off (in the ORCATheory object), otherwise you will end up using 8*8=64 cores

If you send me the outputfiles from ASH including everything generated in the scratch directory during the run (in particular the ORCA outputfiles in the individual image-directories) then I can also take a look

Btw, unnecessary things in your input-script:
- textwrap.dedent() should not be needed. 
- interfaces.interface_knarr.NEB can be replace  by NEB (documentation now updated)

**Comment by Lisa-Phan** [comment]
Hi Ragnar, 

Thank you very much for the suggestions. Changing ORCATheory's process number to 1 removes the error. Though, this does make things a lot slower compared to directly running NEB through Orca, which takes ~1.5 days to converge the 150-cycle optimization compared to 6 cycles in 1 day through ASH/Knarr. I'll recheck the setup to see if I'm making any mistakes.

Another observation which I don't understand yet is how the .gbw read is handled. I had thought that, in order to obtain a broken symmetry wavefunction to use for NEB, one would do a single point spin flip calculation on the images, then read the images into the calculation with the molfiledir option. 

I'd tried to do this to model an antiferromagnetically coupled complex, but it seems like the read-in solution always shows up as ferromagnetic. Have you had any experience with this by any chance? 

The ASH script for this is beneath. I haven't changed the textwrap.dedent and interface.interface_knarr yet just because they most likely won't affect the outcome

"""""""""""""""""""""""
import textwrap 
from ash import *

##################################
# GLOBAL VARIABLES
################################

RELAXED_REACTANT = r"/scratch/09069/dhp563/ash/test/orca_neb/pmul_neb/pmul_file_collection_troubleshoot/broken_sym_NEB/reactant.xyz"
RELAXED_PRODUCT = r"/scratch/09069/dhp563/ash/test/orca_neb/pmul_neb/pmul_file_collection_troubleshoot/broken_sym_NEB/product.xyz"


reactant = Fragment(xyzfile=RELAXED_REACTANT, conncalc=False, charge = 0, mult = 1)
product = Fragment(xyzfile=RELAXED_PRODUCT, conncalc=False, charge = 0, mult = 1)
#NEB-CI job. Final saddlepoint structure stored in new object "Saddlepoint"


#create Orca theory from simple input and blocks
input = "!BP86 def2-SVP TightSCF"
block = textwrap.dedent("""
    %basis
        newgto Fe "def2-TZVP" end
        newgto O "def2-TZVP" end
        newgto N "def2-TZVP" end
    end
                        
    %scf
        CNVZerner True
    end
                                            
    """)

theory_obj = ORCATheory(orcasimpleinput = input, 
                        orcablocks = block, 
                        numcores = 1, 
                        orcadir = r"/work/09069/dhp563/ls6/orcaa/all_three")


Saddlepoint = interfaces.interface_knarr.NEB(reactant = reactant, 
                                             product = product, 
                                             theory = theory_obj, 
                                             images=8, 
                                             CI=True,  
                                             runmode = 'parallel', 
                                             numcores = 10, 
                                             restart_file = r"/scratch/09069/dhp563/ash/test/orca_neb/pmul_neb/pmul_file_collection_troubleshoot/initial_input_NEB/NEB_longer_Fe_MEP_trj.xyz",
                                             mofilesdir = r"/scratch/09069/dhp563/ash/test/orca_neb/pmul_neb/pmul_file_collection_troubleshoot/renamed_gbw_file_0_1")

Saddlepoint.print_system(filename='saddlepoint_PQ.ygg')

"""""""""""""""""""""""

Thank you once again, 
Lisa Phan

**Comment by RagnarB83** [comment]
I can take a closer look tomorrow.

The key thing is though that for NEB parallelization, the following math applies (both for ASH-ORCA and ORCA). 
You first have to choose  between 2 scenarios:   parallelization over images (NEB(runmode='parallel', numcores=X)) vs. Theory-parallelization (ORCATheory(numcores=X)). Because the images can run at the same time then NEB-parallelization is better than parallelizing the Theory-parallelization, i.e. the DFT energy+gradient step, because the DFT step simply can not scale as well. Each energy+gradient calculation will run slower but the overall job will be faster because you can run all images simultaneously (essentially perfect scaling).

- If you have 8 CPU cores available and 8 images and you run NEB in parallel mode, then you can run 8 images at the same time (ORCATheory should have numcores=1). This is better than disabling NEB-parallelization and enabling ORCATheory parallelization).
- If you have 10 CPU cores available and 8 images and you run NEB in parallel mode, then you can run 8 images simultaneously using 1 CPU core for each image (ORCATheory should have numcores=1). 2 available CPU cores are, however, now  wasted i.e. they cannot be used in any way. In this situation you might as well use 10 images instead (could help make the NEB optimization run smoother), or you can reduce the CPU cores to 8 instead.
- If you have 16 CPU cores available and 8 images then you can in principle utilize both NEB-parallelization and Theory-parallelization. Do : NEB(runmode='parallel', numcores=8) and ORCATheory(numcores=2). This was not possible with older OpenMPI versions but should in principle work.
Now 8 images will be run in parallel, i.e. ASH will launch 8 ORCA-processes and each ORCA process should launch 2 MPI processes to give a total of 8*2 = 16


Regarding reading GBW-files. Yes the best thing is to have calculated broken-symmetry solutions before for at least one of the images. You could then create identical GBW files in the directory for all images (simplest) or you can create a BS-solution for each image if you are restarting and have the coordinates available (more robust in principle but more annoying to setup).
There is one little caveat which applies to ORCA's autostart behaviour. If the multiplicity is singlet then ORCA by default assumes a restricted determinant and will not correctly read your broken-symmetry singlet GBW files. You need to turn on UKS for this in the ORCATheory object.

**Comment by Lisa-Phan** [comment]
Hi Ragnar, 

Thank you again for the message. I'd tried out your suggestions ( ASH nproc = 8, Orca nproc = 2, UKS in orca input block) and it seems like everything is running smoothly now. I have one last question on restarting the job at this state. Are the .gbw in each subdirectory Pooljob_image_ suitable to use as the restart .gbw ? I'd tried restarting by reading images from knarr_last_iter.xyz, and apply the broken symmetry treatment on them to obtain new .gbw files. For reasons I don't know, these new singlepoint calculations seem to all have lowered spin density. 

Best regards, 
Lisa Phan

**Comment by RagnarB83** [comment]
Glad to hear it's running smoothly. In principle it should run as smoothly as NEB within ORCA but it's been a while since the parallelization was tested.

Yes, if you want to restart a NEB job where you also restart from the latest orbitals (only a good idea if images were converging to proper broken-symmetry solutions) then you can use the GBW file present in each Pooljob_imageX directory, you would just need to rename each one and copy into the orbitals-directory that you point to. The GBW files should be called :  current_imageX.gbw  where X is each image-number (X can be 0, 1,2,3, etc.). You can make sure that ASH reads these properly by checking the output, the logic of what ASH does should be clearly printed. If ASH does not read them then you will get ORCA guess it's own orbitals and then things will go wrong.

Also: Do not request an ORCA BrokenSym/Flipspin calculation (e.g. via brokensym/atomstoflip keywords in ORCATheory or manually by defining inside orcablocks). If good broken-symmetry solutions were already found for each image in the previous job (check the last ORCA outputfile in each) then all you have to do is to make sure the spin multiplicity of the broken-symmetry solution is specified (mult=1 in your case) and make sure that you have the  "UKS" keyword available in the ORCATheory definition (or things will go wrong when ORCA tries to do RKS automatically for singlet states etc.)

Another possibly useful ORCATheory option to include for these types of job: ORCATheory(..., print_population_analysis=True). This means that ASH will grab the Mulliken charge/spin population information for the ORCA output for each image and print in the ASH output while the job is running (the printlevel of NEB and ORCATheory needs to 2, however). When ASH runs NEB in parallel the output maybe, however, be a little chaotic.

If it does not work then send me the ASH outputfile.

**Comment by RagnarB83** [comment]
Note: There were some flaws in the documentation about the return object from NEB and NEBTS functions that have now been fixed at: https://ash.readthedocs.io/en/latest/neb.html

Btw, when restarting and using the mofilesdir option it is a good idea to carefully check the ASH output to make sure that things are behaving as intended.
Here is an example of when the GBW files are not correctly read (e.g. wrong path or wrongly named files):

> NEB ITERATION: -1
> 
> Images to be computed in this iteration: [0, 9]
> 
> Starting NEB calculations in parallel mode
> 
> Creating worker directory: Pooljob_image_0
> mofilesdir option active for iteration -1. Looking inside /Users/xxxx/Downloads/pmul_file_collection_troubleshoot/gbw_file_only for imagefile: current_image0.gbw
> File /Users/xxxx/Downloads/pmul_file_collection_troubleshoot/gbw_file_only/current_image0.gbw does NOT exist. Continuing.
> 

ASH in this case, however, still chooses to continue and ORCA will use it's own guess orbitals in this case. I may change this so that ASH quits instead when this happens.

When ORCA successfully reads the GBW files you should get instead:

> NEB ITERATION: -1
> 
> Images to be computed in this iteration: [0, 9]
> 
> Starting NEB calculations in parallel mode
> 
> Creating worker directory: Pooljob_image_0
> mofilesdir option active for iteration -1. Looking inside /home/321.5-COMX/321.5.1-Commun/ragnar/ASH-NEB/Fe-BS-LisaPhan/mofiles-dir for imagefile: current_image0.gbw
> File /home/321.5-COMX/321.5.1-Commun/xxxx/ASH-NEB/Fe-BS-LisaPhan/mofiles-dir/current_image0.gbw DOES exist
> Copying file /home/321.5-COMX/321.5.1-Commun/xxxx/ASH-NEB/Fe-BS-LisaPhan/mofiles-dir/current_image0.gbw to dir Pooljob_image_0 as orca.gbw
>

**Comment by Lisa-Phan** [comment]
Hi Ragnar, 

Thanks again for the message. In my case, Knarr NEB job was able to properly read in the coordinates and run starting from iteration -1, with spin densities post single point calculation matching the reported ones in the Pooljob directories. I really appreciate the comments and explanation given above.

**Comment by RagnarB83** [comment]
Great!
